- hosts: webserver
  vars_files:
         - variables
  tasks:
        - name: "installing httpd"
          package:
              name: "httpd"
              state: present
        
        - name: "Creating Document root"
          file:
              state: directory
              dest: "{{ doc_root }}"
  
        - name: "Configuration File"
          template:
             src: "./webserver.j2"
             dest: "/etc/httpd/conf.d/new_conf.conf"
          notify: "server restart"

        - name: "Copy webpages"
          copy:
              content: "<h1> WebPage </h1>"
              dest: "{{ doc_root }}/index.html"
  
        - name: "web Server start"
          service:
              name: "httpd"
              state: started
              enabled: yes
        
        - name: "Adding Firewall rule port {{ port_number }}"
          firewalld:
              port: "{{ port_number }}/tcp"
              permanent: yes
              state: enabled
              immediate: yes
                  
  handlers:
        - name: "server restart"
          service:
               name: "httpd"
               state: restarted
